[project]
name = "spatial-graphql-sandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
spatial-graphql-sandbox = "spatial_graphql_sandbox:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "meltano>=4.3.0",
]
